version: '3.7'

x-common-migration: &common-migration
  POSTGRES_HOST: ffc-demo-payment-postgres
  SCHEMA_ROLE: ${SCHEMA_ROLE:-postgres}
  SCHEMA_PASSWORD: ${SCHEMA_PASSWORD:-ppp}
  SCHEMA_NAME: ${SCHEMA_NAME:-public}

x-common-postgres: &common-postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: ffc_demo_payments
  POSTGRES_PASSWORD: ppp
  POSTGRES_USERNAME: postgres

services:  
  schema-up:
    image: liquibase/liquibase:3.10.x
    environment:
      << : *common-migration
      << : *common-postgres
    entrypoint: >
      sh -c "/scripts/migration/schema-up"
    volumes:
      - ./changelog/:/liquibase/changelog/
      - ./scripts/:/scripts/
      
  schema-down:
    image: liquibase/liquibase:3.10.x
    environment:
      << : *common-migration
      << : *common-postgres
    entrypoint: >
      sh -c "/scripts/migration/schema-down"
    volumes:
      - ./changelog/:/liquibase/changelog/
      - ./scripts/:/scripts/

