version: '3.7'

x-common-migration: &common-migration
  POSTGRES_HOST: ${POSTGRES_HOST}
  SCHEMA_ROLE: ${POSTGRES_SCHEMA_ROLE:-postgres}
  SCHEMA_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD}
  SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME}
  POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
  POSTGRES_USERNAME:  ${POSTGRES_ADMIN_USERNAME}
  POSTGRES_PORT: 5432
  POSTGRES_DB: ${POSTGRES_DB}

services:
  schema-up:
    image: liquibase/liquibase:3.10.x
    environment:
      << : *common-migration
    entrypoint: >
      sh -c "/scripts/schema-up"
    volumes:
      - ./changelog/:/liquibase/changelog/
      - ./scripts/:/scripts/
      
  schema-down:
    image: liquibase/liquibase:3.10.x
    environment:
      << : *common-migration
    entrypoint: >
      sh -c "/scripts/schema-down"
    volumes:
      - ./changelog/:/liquibase/changelog/
      - ./scripts/:/scripts/

