#!/usr/bin/env bash

tag=$1
sha=$2
major=$(echo "$tag" | cut -d. -f1)
minor=$(echo "$tag" | cut -d. -f1,2)

echo "Updating MAJOR ($major) tag to point to $sha"
git push origin ":refs/tags/$major"
git tag -f "$major" "$sha"
git push origin "$major"

echo "Updating MINOR ($minor) tag to point to $sha"
git push origin ":refs/tags/$minor"
git tag -f "$minor" "$sha"
git push origin "$minor"
