#!/bin/sh

# Uses globally installed `@commitlint/{cli,config-conventional}`.
# Executed by `commit-msg` Git hook (if setup). Runs on .git/COMMIT_EDITMSG.
commitlint --edit --verbose --config .commitlintrc.json \
  --extends "$(npm config get prefix)/lib/node_modules/@commitlint/config-conventional"
