#!/bin/sh

projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

docker build --tag defra/ffc-jenkins-pipeline-library-commitlint --file commitlint.Dockerfile .
docker run -t --rm -v "$projectRoot"/:/home/node/wrk defra/ffc-jenkins-pipeline-library-commitlint --from origin/master --to HEAD --verbose --extends @commitlint/config-conventional --config .commitlintrc.json
