#!/usr/bin/env sh

projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

# Run [GitHub Super-Linter](https://github.com/github/super-linter/blob/master/docs/run-linter-locally.md) locally to lint Groovy code
docker run -e RUN_LOCAL=true -e VALIDATE_GROOVY=true -e VALIDATE_BASH=true "$@" -v "$projectRoot"/:/tmp/lint github/super-linter
