#!/bin/sh

projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

imageName=defra/ffc-jenkins-pipeline-library-semantic-release

docker build --tag $imageName --file semantic-release.Dockerfile .

docker run -t --rm -v "$projectRoot":/home/node/wrk \
  -e GH_TOKEN="$GH_TOKEN" $imageName --debug --dry-run
