#!/bin/sh

projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

docker build --tag defra/ffc-jenkins-pipeline-library-semantic-release --file semantic-release.Dockerfile .
docker run -e GH_TOKEN="$GH_TOKEN" -t --rm -v "$projectRoot"/:/home/node/wrk defra/ffc-jenkins-pipeline-library-semantic-release --debug
