#!/bin/sh

echo '********************in container, entering'
whoami
# ensure tags are up to date to avoid clobbering messages
git fetch --tags -f
ls -lah
ls -lah .git
cat .git/FETCH_HEAD
npx semantic-release --debug --dry-run
echo '********************in container, leaving'
