#!/usr/bin/env bash

tag=$1
version=$2
type=$3

major=$(echo "$tag" | cut -d. -f1)
minor=$(echo "$tag" | cut -d. -f1,2)

echo "Next release will be a '$type' version."
echo "It will be tagged as 'v-$version', '$minor' & '$major'."
