name: Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  superlinter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FORMAT: tap
        VALIDATE_GROOVY: true
    - name: Archive report and log
      uses: actions/upload-artifact@v2
      with:
        name: super-linter-report-and-log
        path: ./super-linter.*
